name = "worker-name"
main = "src/index.ts"
compatibility_date = "2022-08-08"

[dev]
port=8002

[env.stg]
name = "worker-name-stg"

[env.prd]
name = "worker-name"

[vars]
# The necessary secrets are:
# - 
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
ENVIRONMENT = "stg"

[env.stg.vars]
ENVIRONMENT = "stg"

[env.prd.vars]
ENVIRONMENT = "prd"
